/**
 * Main type exports - barrel file for all type definitions
 * This file serves as the central export point for all types used throughout the application
 */

// Common utility types
export type {
  BaseComponentProps,
  FormComponentProps,
  ModalProps,
  LoadingState,
  PaginationParams,
  PaginationResponse,
  SelectOption,
  ExtendedSelectOption,
  FilterParams,
  SortParams,
  Address,
  Hash,
  Timestamp,
  ID,
  ContractStandard,
  TransactionStatus,
  HttpMethod,
  AsyncResult,
  VoidCallback,
  ValueCallback,
  AsyncCallback,
  AsyncValueCallback,
} from './common';

// API-related types
export type {
  ApiError,
  ApiResponse,
  ApiRequestOptions,
  UseApiReturn,
  User,
  AuthState,
  Chain,
  ChainApiResponse,
  TimelockContract,
  TimelockParameters,
  ImportTimelockRequest,
  CreateTimelockRequestBody,
  TimelockApiResponse,
  Transaction,
  TransactionListResponse,
  TransactionStats,
  CreateTransactionRequest,
  TransactionListFilters,
  PendingTransactionFilters,
  ABIItem,
  ABIListResponse,
  EmailNotification,
  EmailNotificationListResponse,
  EmailLog,
  CreateEmailNotificationRequest,
  UpdateEmailNotificationRequest,
  VerifyEmailRequest,
  ResendCodeRequest,
  EmergencyReplyRequest,
  EmailNotificationFilters,
  Partner,
  SponsorsData,
  SponsorsApiResponse,
  AssetsData,
  UseAssetsApiReturn,
} from './api';

// Blockchain and Web3 types
export type {
  DeploymentResult,
  TransactionResult,
  CompoundTimelockParams,
  OpenZeppelinTimelockParams,
  DeployContractParams,
  SendTransactionParams,
  Web3State,
  UseWeb3Return,
  ChainConfig,
  ChainIdMapping,
  TimelockABI,
  ContractValidationResult,
  NetworkInfo,
  GasEstimation,
  TransactionReceipt,
  WalletConnectionOptions,
  ContractCallParams,
  ContractReadResult,
  ContractWriteResult,
  TimelockAdminPermissions,
  TimelockOperation,
  MultiSigWallet,
  TokenInfo,
  TokenBalance,
} from './blockchain';

// Component prop types
export type {
  ButtonVariant,
  ButtonSize,
  ButtonProps,
  InputProps,
  SelectProps,
  RadioButtonOptionProps,
  ChainOption,
  StandardOption,
  StandardOptionConfig,
  ParameterDisplayRowProps,
  FirstTimeTimelockIntroProps,
  ContractStandardSelectionProps,
  CreationDetails,
  DialogDetailsState,
  ConfirmCreationDialogProps,
  CreateTimelockFormProps,
  CreateTimelockFormState,
  EncodingTransactionFormProps,
  TargetABISectionProps,
  MailboxSelectionProps,
  EncodingPreviewProps,
  AddABIFormProps,
  ABIContent,
  ViewABIFormProps,
  ABIRow,
  LoadingSpinnerProps,
  ErrorBoundaryProps,
  ToastProps,
  DataTableColumn,
  DataTableProps,
  FormFieldProps,
  CardProps,
  TabsProps,
  DrawerProps,
} from './components';

// Form-related types
export type {
  FormError,
  FormState,
  FormFieldConfig,
  UseFormReturn,
  LoginFormData,
  CreateTimelockFormData,
  ImportTimelockFormData,
  CreateTransactionFormData,
  EmailNotificationFormData,
  ABIFormData,
  ProfileFormData,
  SettingsFormData,
  SearchFormData,
  FilterFormData,
  ValidationSchemas,
  FormProps,
  FormFieldProps as FormFieldComponentProps,
  FormSectionProps,
  FormActionsProps,
  DynamicFormField,
  DynamicFormConfig,
  FormWizardStep,
  FormWizardConfig,
  FormWizardProps,
} from './forms';

// Re-export commonly used React types for convenience
export type { ReactNode, ComponentProps, FC, PropsWithChildren } from 'react';